common: &common
  adapter: postgresql
  username: <%= ENV['USER'] %>

development:
  database: bushfire_development
  <<: *common

test:
  database: bushfire_test
  <<: *common

cucumber:
  database: bushfire_test
  <<: *common

production:
  database: bushfire_production
  <<: *common
